apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
  labels:
    app: fastapi-server
spec:
  selector:
    matchLabels:
      app: fastapi-server
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
        - name: fastapi-server
          image: gabrielloliveira/fastapi-helloworld:latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "0.1" # 0.1 core ou 100m
              memory: "100Mi" # 100 MiB
            limits:
                cpu: "0.1" # 0.1 core ou 100m
                memory: "100Mi" # 100 MiB

          ports:
            - name: fastapi-server
              containerPort: 80
              protocol: TCP

          envFrom:
            - configMapRef:
                name: fastapi-server-env
            - secretRef:
                name: fastapi-server-secret

          startupProbe:
            httpGet:
              port: 80
              path: /healthz
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 10
            failureThreshold: 1

          livenessProbe:
            httpGet:
              port: 80
              path: /healthz
            periodSeconds: 20
            failureThreshold: 1

      restartPolicy: Always