apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
  labels:
    app: fastapi-server
spec:
  selector:
    matchLabels:
      app: fastapi-server
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
        - name: fastapi-server
          image: gabrielloliveira/fastapi-helloworld:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: fastapi-server
              containerPort: 80
              protocol: TCP
      restartPolicy: Always