apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-service
spec:
  selector:
    app: fastapi-server
  ports:
    - name: fastapi-server-service
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP # ClusterIP | NodePort | LoadBalancer
  